# Generated by Django 5.1.3 on 2024-12-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_shop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Default Product Name', max_length=255),
        ),
    ]
