# Generated by Django 5.1.3 on 2024-12-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
